# Generated by Django 3.2.12 on 2022-03-31 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceimage',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
